/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreedsImageDialog: typeof import('./components/Dialogs/BreedsImageDialog.vue')['default']
    CustomButton: typeof import('./components/customComponents/CustomButton.vue')['default']
    CustomCard: typeof import('./components/customComponents/CustomCard.vue')['default']
    CustomDialog: typeof import('./components/customComponents/CustomDialog.vue')['default']
    CustomNavBar: typeof import('./components/customComponents/CustomNavBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
